<style type="text/css">
    
    #side-container{}
    .side-box {border:1px solid #ccc;width:210px;margin:0px 15px 15px 0px;padding:5px;-moz-box-shadow: 0 0 5px #ddd;-webkit-box-shadow: 0 0 5px#ddd;box-shadow: 0 0 5px #ddd;}
    .side-separator {width:95%;border-bottom:1px dotted #ccc;padding-left:10px;}
    
    #side-box-1 {}
    #side-box-2 {}
    
    ul {list-style-type: none;padding:5px;margin:0px;font-size:11px;line-height:13px;}
    ul li span {color:#336699;padding-right:4px;}
    
    #registration-steps {text-align:center;font-size:16px;font-weight:bold;border-bottom:1px solid #ccc;padding:5px;}
    #registration {font-size:14px; font-weight: bold;color:#333333;}
    #questions {margin-top:5px;font-size:11px;}
    
    a.side-link {text-decoration:none;color:#333333;}
    a.side-link:link {color:#333333;}
    a.side-link:hover {color:#336699;}
    
    .triangle {font-size:8px;}
    
</style>

<div id="side-container">
    
    <div class="side-box" id="side-box-1">

        <div id="registration-steps">Registration Steps</div>

        <ul id="side-list">
            <li><span class="triangle">&#9658;</span><a href="/" class="side-link">Log-in from Home Page</a></li>
            <li><span class="triangle">&#9658;</span><a href="/agenda" class="side-link">Agenda</a></li>
            <li><span class="triangle">&#9658;</span><a href="/accommodations" class="side-link">Hotel Accommodations</a></li>
        </ul>
        
        <!--
        <div class="side-separator"></div>
        -->

    </div>

    <!--
    <div class="side-box" id="side-box-2">

        <div id="questions">
            <b>Questions?</b>  Click below to email us with any questions you have about the program.
        </div>

        <ul>
            <li><span class="triangle">&#9658;</span><a href="mailto:Angela.Bien@bmwna.com" class="side-link">Email Us</a></li>
        </ul>
    </div>    
    -->
    
</div>

