<h3>User Detail</h3>

<table width="100%" align="center" style="padding:15px;">
    <tr>
        <td><span class="site-label-1">ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Date Created:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["date_created"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Last Updated:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["last_updated"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">User:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["user"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Active:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["active"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">User ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["user_id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Password:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["password"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Role ID:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["role_id"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">First Name:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["first_name"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Last Name:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["last_name"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Email:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["email"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Q Number:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["q_number"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Employee Number:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["emp_no"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Title:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["title"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Check-in Date:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["check_in_date"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Check-out Date:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["check_out_date"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Early Check-in:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["early_check_in"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Late Check-out:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["late_check_out"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Transportation:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["transportation"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Arrival Flight Info:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["arrival_flight_info"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Arrival Flight Time:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["arrival_flight_time"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Departure Flight Info:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["departure_flight_info"];?></span></td>
    </tr>
    <tr>
        <td><span class="site-label-1">Departure Flight Time:</span></td>
        <td><span class="site-label-2"><?php echo $this->users["departure_flight_time"];?></span></td>
    </tr>
</table>